version: '3.9'

services:
  nginx:
    image: loadbalancer:latest
    container_name: loadbalancer
    volumes:
      - ~/ssl_certs:/letsencrypt
      - ~/ssl_certs/certs:/etc/letsencrypt
      - ~/ssl_certs/conf.d:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
